version: '3'
services:
  app:
    container_name: node-mongo-app
    volumes:
      - /usr/src/app
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - app-network
  
  mongo:
    container_name: mongo
    image: mongo
    restart: always 
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
      
volumes:
  mongo-data:

networks:
  app-network: